/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "my.domain/guestbook/apis/apps/v1alpha1"
)

// FakeGuestBooks implements GuestBookInterface
type FakeGuestBooks struct {
	Fake *FakeMyV1alpha1
	ns   string
}

var guestbooksResource = v1alpha1.SchemeGroupVersion.WithResource("guestbooks")

var guestbooksKind = v1alpha1.SchemeGroupVersion.WithKind("GuestBook")

// Get takes name of the guestBook, and returns the corresponding guestBook object, and an error if there is any.
func (c *FakeGuestBooks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GuestBook, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(guestbooksResource, c.ns, name), &v1alpha1.GuestBook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GuestBook), err
}

// List takes label and field selectors, and returns the list of GuestBooks that match those selectors.
func (c *FakeGuestBooks) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GuestBookList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(guestbooksResource, guestbooksKind, c.ns, opts), &v1alpha1.GuestBookList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.GuestBookList{ListMeta: obj.(*v1alpha1.GuestBookList).ListMeta}
	for _, item := range obj.(*v1alpha1.GuestBookList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested guestBooks.
func (c *FakeGuestBooks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(guestbooksResource, c.ns, opts))

}

// Create takes the representation of a guestBook and creates it.  Returns the server's representation of the guestBook, and an error, if there is any.
func (c *FakeGuestBooks) Create(ctx context.Context, guestBook *v1alpha1.GuestBook, opts v1.CreateOptions) (result *v1alpha1.GuestBook, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(guestbooksResource, c.ns, guestBook), &v1alpha1.GuestBook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GuestBook), err
}

// Update takes the representation of a guestBook and updates it. Returns the server's representation of the guestBook, and an error, if there is any.
func (c *FakeGuestBooks) Update(ctx context.Context, guestBook *v1alpha1.GuestBook, opts v1.UpdateOptions) (result *v1alpha1.GuestBook, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(guestbooksResource, c.ns, guestBook), &v1alpha1.GuestBook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GuestBook), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGuestBooks) UpdateStatus(ctx context.Context, guestBook *v1alpha1.GuestBook, opts v1.UpdateOptions) (*v1alpha1.GuestBook, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(guestbooksResource, "status", c.ns, guestBook), &v1alpha1.GuestBook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GuestBook), err
}

// Delete takes name of the guestBook and deletes it. Returns an error if one occurs.
func (c *FakeGuestBooks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(guestbooksResource, c.ns, name, opts), &v1alpha1.GuestBook{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGuestBooks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(guestbooksResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.GuestBookList{})
	return err
}

// Patch applies the patch and returns the patched guestBook.
func (c *FakeGuestBooks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GuestBook, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(guestbooksResource, c.ns, name, pt, data, subresources...), &v1alpha1.GuestBook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GuestBook), err
}
