apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha.my.domain
spec:
  insecureSkipTLSVerify: true
  group: my.domain
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: cicd-apiserver
    namespace: cicd-apiserver
  version: v1alpha